sudo: false
dist: trusty
language: php
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      secure: lpSUbB9rJu/owy0mAbMUU46uA9AY1yujHMdSsH+1n+1BS7Z8qa68mfwTT37dzwSwkrdglhQwPp92p0h2C1jUZR1+tMWDZUXgF5wR50i/NrnqZnT+YpdOFtErQ2O85CoE2TPq9yCgrfZABWoesoUStrqyNn1I7JW13whgxqpRKQXFEy5YPZOC5HxgXGNK6hAThcAUSOMbbp7n7ogMyYQmavUFoPBfBrmjK32ZUQHhCaCjL0znGfHknE1f1xam1TgOxy1PrWLE5PXj5JH+yeRQdOo7kD3QtnP5i6kYT28dp9nVcgooJhrtm04p60TTqhRVBHINAp04LW8f7JiVcMMBqX+O3pwo95kwDWzcSDz+WNVbxM3wn50BN26HbaySyzBEfwIqBk5erBx24IwoJU2FlNAMlR36vhs9OG94LrJO72bm20ohbxMkcCGRQAKr169jYicfCLwm68z9WT/k3NqJv4pi+ZQ0w+69aGZ0u1YtzlKguB6iLmCUo+YrxWLSmXAPBGfoRkbJkm+z5AElbu+hd6tOLcGM+YyKfVetTUJc55yOKy66VDgjzUkEr0LJ/ir2CGJ69W13fULemO/xHpuydDAA4112Zc55s+WszqRnLfhWhXjWOKT5jewHvpk0ds6BIPxO3WWxTwh8GtS0kL2IGGtF0bKF2YEvAftKT2pKrKU=
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.composer/cache"
matrix:
  include:
  - php: 7.1
    env: WP_VERSION=latest
  - php: 7.0
    env: WP_VERSION=latest
  - php: 5.6
    env: WP_VERSION=4.4
  - php: 5.6
    env: WP_VERSION=latest
  - php: 5.6
    env: WP_VERSION=trunk
  - php: 5.6
    env: WP_TRAVISCI=phpcs
  - php: 5.3
    env: WP_VERSION=latest
    dist: precise
before_script:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- |
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    phpenv config-rm xdebug.ini
  else
    echo "xdebug.ini does not exist"
  fi
- |
  if [[ ! -z "$WP_VERSION" ]] ; then
    bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    composer global require "phpunit/phpunit=4.8.*|5.7.*"
  fi
- |
  if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
    composer global require wp-coding-standards/wpcs
    phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
  fi
script:
- |
  if [[ ! -z "$WP_VERSION" ]] ; then
    phpunit
    WP_MULTISITE=1 phpunit
  fi
- |
  if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
    phpcs
  fi
